### ISSUE TITLE
MELPA?

### ISSUE THREAD

**Issue by ishmael1851** [DoMiNeLa10/json-mode#4]
This is a great package!  Would it be possible to put it on MELPA, so it's easier to install?  I was confused, because there's already a package there called "json-mode", but it's not nearly as nice as yours.

**Comment by UwUnyaa** [comment]
I think I'd have to rename it to avoid conflicts, and look into how to publish it there.

If you want to use it right now, it's trivial to set it up with straight.el, which can pull repos from github easily.

**Comment by UwUnyaa** [comment]
I am not sure whether this mode would be accepted in the first place after reading through their documentation, and a better way to go about this might be to try to add features from this mode to the other one. I think I'll try getting into MELPA with packages that don't have duplicates first.

**Comment by UwUnyaa** [comment]
It seems like that project might be dead, and some more action might be needed to bring it up to date. I've raised an issue to check whether the project is dead, and if I find that that is indeed the case, I'll think of doing something such as taking onto that repository and it's maintenance myself.

https://github.com/joshwnj/json-mode/issues/64

**Comment by UwUnyaa** [comment]
Considering that the upstream project is dead, and that I don't feel confident enough to take over someone's codebase that's been stale for a long time by now, I think the best way forward would be to ask someone who can take over upstream and then I could make pull requests there.

@ishmael1851 do you know any good way to get in touch with MELPA maintainers?

**Comment by danielpza** [comment]
Hey @UwUnyaa I have a couple of questions if you don't mind.

- Did you got to publish the package?
- How is it related to the original json-mode, is it a fork or did you make from scratch?
- Are you accepting PRs?

**Comment by UwUnyaa** [comment]
@danielpza
>Did you got to publish the package?

Since there's a similar package in MELPA, it wouldn't be accepted.

>How is it related to the original json-mode, is it a fork or did you make from scratch?

I wrote this mode from scratch, and I've tried to reimplement features of my mode in a fork for that, but I got stuck with getting my timer-based validation to work properly in Emacs 27.

>Are you accepting PRs?

Sure, although I think the best way forward is to merge my features into already existing json-mode to get them into a package in a public repository.

**Comment by orzechowskid** [comment]
it appears there have been no commits to the joshwnj/json-mode repo for two years now, and there are multiple open issues and PRs against it.  I wonder if or when it's appropriate to fork that repo, apply your changes, then open a PR against MELPA .  Their [contributors' guide](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org) does mention that packages can be transferred.

(of course, there's always straight.el and other package-management tools which allow one to use source-control repos as package sources.)

**Comment by UwUnyaa** [comment]
In any case, I should have a forked repo up on my github, and straight.el should make it work without any issue. I don't feel like taking on maintenance of MELPA packages right now due to personal reasons, this sort of thing would have to happen in the future.

**Comment by dawinSoft** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.KrzysztofKowalski, @ducksunderdoors, @NoisyNot, @efyang, @Azeril, @IFarhankhan, @bmorelax, @alexander-irbis, @francisjsun, @alpharde, @wildaces215, @x13945, @kutepoyzon, @OrAsaf, @ashfinal, @Jean-Emile, @matheusnervis, @AndersTao, @vladei, @xt1993

**Comment by UwUnyaa** [comment]
I'm not planning to collaborate with MELPA in any capacity due to their way of handling things. I should've closed this bug report years ago.
