### ISSUE TITLE
Object key highlighting

### ISSUE THREAD

**Issue by galdor** [DoMiNeLa10/json-mode#6]
While this package has really nifty features (folding is incredibly useful), the fact that it highlights object keys and strings the same way makes large documents much less readable. Given that the mode is based on js-mode, would there be a way to change this ? I'm not really familiar with font-lock in general, but you may have an idea :)

**Comment by UwUnyaa** [comment]
I forgot to mention it in the readme, but this project is considered abandoned, use https://github.com/joshwnj/json-mode instead. I still haven't gotten to backporting features of my mode there due to issues I ran into.
